# Generated by Django 6.0 on 2026-01-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя гостя')),
                ('contact', models.CharField(max_length=100, verbose_name='Телефон/Контакт')),
                ('date', models.CharField(max_length=100, verbose_name='Дата и время')),
                ('guests', models.CharField(max_length=50, verbose_name='Кол-во гостей')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Бронь стола',
                'verbose_name_plural': 'Брони столов',
                'ordering': ['-created_at'],
            },
        ),
    ]
