# Generated by Django 6.0 on 2026-01-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Событие'),
        ),
    ]
