# Generated by Django 6.0 on 2026-01-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID поста в Telegram')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок (авто или вручную)')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Афиша')),
                ('event_date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Событие/Афиша',
                'verbose_name_plural': 'Афиша',
                'ordering': ['-event_date'],
            },
        ),
    ]
