"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from django.utils.translation import gettext_lazy as _

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['daerdree.bar', 'www.daerdree.bar', '193.181.208.36', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'ckeditor',
    'boardgames',
    'menu',
    'bookings',
    'events',
    'cms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/



from django.utils.translation import gettext_lazy as _  # <--- ДОБАВИТЬ ИМПОРТ

LANGUAGE_CODE = 'ru'  # <--- ЛУЧШЕ ПОМЕНЯТЬ ПО УМОЛЧАНИЮ НА 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# <--- ДОБАВИТЬ ЭТОТ БЛОК ЦЕЛИКОМ --->
LANGUAGES = [
    ('ru', _('Russian')),
    ('en', _('English')),
]

MODELTRANSLATION_DEFAULT_LANGUAGE = 'ru'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://daerdree.bar",
    "https://www.daerdree.bar"
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://daerdree.bar",
    "https://www.daerdree.bar"
]

STATIC_ROOT = BASE_DIR / 'staticfiles'  # Папка, куда соберется вся статика
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# =============================================================================
# SECURITY HEADERS (SEO & hardening)
# =============================================================================
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source']
        ],
        'width': '100%',
    }
}

# =============================================================================
# DJANGO JAZZMIN — настройка админки под бренд Daerdree
# =============================================================================

JAZZMIN_SETTINGS = {
    # заголовок окна браузера
    "site_title": "Daerdree Admin",

    # заголовок на странице входа
    "site_header": "Daerdree Admin",

    # текст на брендовой полоске (html-теги не поддерживаются, только текст)
    "site_brand": "Daerdree",

    # логотип (относительно static/)
    "site_logo": "admin/img/daerdree.png",

    # логотип для тёмной темы (Django 5+)
    "site_logo_dark": "admin/img/daerdree.png",

    # favicon
    "site_icon": "admin/img/daerdree.png",

    # Welcome text on the login screen
    "welcome_sign": "Войдите в панель управления Daerdree",

    # Copyright on the footer
    "copyright": "Daerdree Bar & Timeclub",

    # List of model admins to search from the search bar
    "search_model": [
        "auth.User",
        "boardgames.BoardGame",
        "events.Event",
    ],

    # Link to your Brand logo on login screen
    "site_logo_css": "max-height: 60px; width: auto;",

    # Field name on user model that contains avatar image
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    # Links on top menu
    "topmenu_links": [
        {"name": "Дашборд", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "На сайт", "url": "/", "new_window": True},
        {"model": "auth.User"},
    ],

    #############
    # User Menu #
    #############

    "usermenu_links": [
        {"name": "Профиль", "model": "auth.User"},
    ],

    #############
    # Side Menu #
    #############

    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # Order of apps
    "order_with_respect_to": [
        "events",
        "boardgames",
        "bookings",
        "cms",
        "auth",
    ],

    # Custom icons for apps/models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "events.Event": "fas fa-calendar-alt",
        "boardgames.BoardGame": "fas fa-dice-d6",
        "boardgames.Category": "fas fa-tags",
        "boardgames.Tag": "fas fa-cogs",
        "boardgames.Expansion": "fas fa-puzzle-piece",
        "bookings.Booking": "fas fa-clipboard-list",
        "cms.SiteTranslation": "fas fa-language",
    },

    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############

    # Relative paths to custom CSS/JS
    "custom_css": "admin/css/admin_custom.css",
    "custom_js": None,

    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,

    ###############
    # Change view #
    ###############

    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.User": "collapsible",
        "auth.Group": "collapsible",
    },

    # Добавляем иконку Font Awesome
    "icons_prefix": "fas",
}


JAZZMIN_UI_TWEAKS = {
    # Базовая тема: darkly — тёмная, близкая к Daerdree
    "theme": "darkly",

    # Цветовая схема (primary = наш teal-акцент)
    "primary": "hsl(187, 83%, 26%)",

    # Показывать границу между карточками
    "card_border": False,

    # Стиль кнопок
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },

    # Темный сайдбар
    "dark_mode_theme": "darkly",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "sidebar": "sidebar-dark-primary",
}