# Generated by Django 6.0 on 2025-12-27 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL Slug')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Иконка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='attribute_icons/', verbose_name='Иконка (SVG/PNG)')),
            ],
            options={
                'verbose_name': 'Механика/Тег',
                'verbose_name_plural': 'Механики и Теги',
            },
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название игры')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/', verbose_name='Фото коробки')),
                ('min_players', models.PositiveIntegerField(default=2, verbose_name='Мин. игроков')),
                ('max_players', models.PositiveIntegerField(default=4, verbose_name='Макс. игроков')),
                ('play_time', models.PositiveIntegerField(help_text='Пример: 45', verbose_name='Среднее время (мин)')),
                ('difficulty', models.IntegerField(choices=[(1, 'Очень легко'), (2, 'Легко'), (3, 'Средне'), (4, 'Сложно'), (5, 'Хардкор')], default=2, verbose_name='Сложность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте?')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boardgames.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, to='boardgames.tag', verbose_name='Механики')),
            ],
            options={
                'verbose_name': 'Настольная игра',
                'verbose_name_plural': 'Настольные игры',
                'ordering': ['title'],
            },
        ),
    ]
