# Generated by Django 6.0 on 2026-03-29 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='setup_image',
            field=models.ImageField(blank=True, null=True, upload_to='games/setups/', verbose_name='Фото расклада'),
        ),
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название дополнения')),
                ('description', models.TextField(blank=True, verbose_name='Описание дополнения')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expansions', to='boardgames.boardgame', verbose_name='Основная игра')),
            ],
            options={
                'verbose_name': 'Дополнение',
                'verbose_name_plural': 'Дополнения',
            },
        ),
    ]
