# Generated by Django 6.0 on 2026-04-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0004_remove_boardgame_description_af_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='expansion',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание дополнения'),
        ),
        migrations.AddField(
            model_name='expansion',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание дополнения'),
        ),
        migrations.AddField(
            model_name='expansion',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название дополнения'),
        ),
        migrations.AddField(
            model_name='expansion',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название дополнения'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название'),
        ),
    ]
