# Generated by Django 6.0 on 2026-05-07 06:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0005_category_description_en_category_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='category',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='games', to='boardgames.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='expansion',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание дополнения'),
        ),
        migrations.AlterField(
            model_name='expansion',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание дополнения'),
        ),
        migrations.AlterField(
            model_name='expansion',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание дополнения'),
        ),
    ]
