# Generated by Django 6.0 on 2026-07-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0006_remove_boardgame_category_boardgame_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='bgg_type',
            field=models.CharField(blank=True, default='boardgame', max_length=50, verbose_name='Тип игры (BGG)'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='designer',
            field=models.CharField(blank=True, max_length=300, verbose_name='Создатель'),
        ),
    ]
