# Generated by Django 6.0 on 2026-07-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0007_boardgame_bgg_type_boardgame_designer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='games/gallery/', verbose_name='Изображение')),
                ('image_type', models.CharField(choices=[('cover', 'Обложка'), ('background', 'Фон'), ('gallery', 'Галерея')], default='gallery', max_length=20, verbose_name='Тип изображения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('alt', models.CharField(blank=True, max_length=300, verbose_name='Alt-текст')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boardgames.boardgame', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Изображение игры',
                'verbose_name_plural': 'Изображения игр',
                'ordering': ['order'],
            },
        ),
    ]
