# Generated by Django 6.0 on 2025-12-27 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Категория меню',
                'verbose_name_plural': 'Категории меню',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание/Состав')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='Объем/Вес')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Вегетарианское?')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menucategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо/Напиток',
                'verbose_name_plural': 'Блюда и Напитки',
                'ordering': ['name'],
            },
        ),
    ]
